/* This file is part of TraceMetrics
 *
 * TraceMetrics is a trace file analyzer for Network Simulator 3 (www.nsnam.org).
 * The goal is to calculate useful metrics for research and performance measurement.
 * URL: www.tracemetrics.net
 *
 * Copyright (C) 2012  Luiz Felipe Zafra Saggioro
 * Copyright (C) 2012  Flavio Barbieri Gonzaga
 * Copyright (C) 2012  Reuel Ramos Ribeiro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package analyzer.gui;

import analyzer.controller.Analyzer;
import analyzer.controller.DefaultProperties;
import analyzer.controller.Utils;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.Properties;

/**
 *
 * Frame that contains the options of the program.
 *
 * @since 1.0.0
 */
public class Options extends javax.swing.JFrame {

    private static Options instance = null;
    private static Properties properties = new Properties(DefaultProperties.getDefaultValues());

    public static String getProperty( String key ) {
        return (String) properties.get(key);
    }

    public static void setProperty( String key, String value ) {
        properties.setProperty(key, value);
    }

    public static Options getInstance() {

        if ( instance == null ) {

            instance = new Options();

        }

        return instance;
    }

    /**
     * Creates new form Options
     */
    private Options() {
        initComponents();

        Point location = Utils.getCentralCoords(Toolkit.getDefaultToolkit().getScreenSize(), this.getBounds());
        this.setLocation(location);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTP_OptionsTabs = new javax.swing.JTabbedPane();
        jP_Alerts = new javax.swing.JPanel();
        jP_AlertsContent = new javax.swing.JPanel();
        stopNoLength = new javax.swing.JCheckBox();
        showAlerts = new javax.swing.JCheckBox();
        jB_ButtonOK = new javax.swing.JButton();
        jB_ButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jP_AlertsContent.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jP_AlertsContent.setToolTipText("");

        stopNoLength.setSelected(true);
        stopNoLength.setText("Stop analysis if a protocol without length field is found");

        showAlerts.setSelected(true);
        showAlerts.setText("Show recoverable error window alerts (the analysis will be paused) ");

        javax.swing.GroupLayout jP_AlertsContentLayout = new javax.swing.GroupLayout(jP_AlertsContent);
        jP_AlertsContent.setLayout(jP_AlertsContentLayout);
        jP_AlertsContentLayout.setHorizontalGroup(
            jP_AlertsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AlertsContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_AlertsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stopNoLength)
                    .addComponent(showAlerts))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jP_AlertsContentLayout.setVerticalGroup(
            jP_AlertsContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_AlertsContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stopNoLength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showAlerts)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jP_AlertsLayout = new javax.swing.GroupLayout(jP_Alerts);
        jP_Alerts.setLayout(jP_AlertsLayout);
        jP_AlertsLayout.setHorizontalGroup(
            jP_AlertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_AlertsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_AlertsContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_AlertsLayout.setVerticalGroup(
            jP_AlertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_AlertsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_AlertsContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTP_OptionsTabs.addTab("Alerts", jP_Alerts);

        jB_ButtonOK.setText("OK");
        jB_ButtonOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jB_ButtonOKMouseReleased(evt);
            }
        });

        jB_ButtonCancel.setText("Cancel");
        jB_ButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jB_ButtonCancelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jB_ButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jB_ButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addComponent(jTP_OptionsTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTP_OptionsTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_ButtonOK)
                    .addComponent(jB_ButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_ButtonOKMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_ButtonOKMouseReleased

        Analyzer.setStopBecauseOfNoLengthProto(stopNoLength.isSelected());
        Analyzer.setShowExceptionMessages(showAlerts.isSelected());
        dispose();

    }//GEN-LAST:event_jB_ButtonOKMouseReleased

    private void jB_ButtonCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_ButtonCancelMouseReleased
        dispose();
    }//GEN-LAST:event_jB_ButtonCancelMouseReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_ButtonCancel;
    private javax.swing.JButton jB_ButtonOK;
    private javax.swing.JPanel jP_Alerts;
    private javax.swing.JPanel jP_AlertsContent;
    private javax.swing.JTabbedPane jTP_OptionsTabs;
    private javax.swing.JCheckBox showAlerts;
    private javax.swing.JCheckBox stopNoLength;
    // End of variables declaration//GEN-END:variables
}
