/* This file is part of TraceMetrics
 *
 * TraceMetrics is a trace file analyzer for Network Simulator 3 (www.nsnam.org).
 * The goal is to calculate useful metrics for research and performance measurement.
 * URL: www.tracemetrics.net
 *
 * Copyright (C) 2012  Luiz Felipe Zafra Saggioro
 * Copyright (C) 2012  Flavio Barbieri Gonzaga
 * Copyright (C) 2012  Reuel Ramos Ribeiro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package analyzer.gui.bug;

import analyzer.controller.Utils;
import analyzer.recoverable_exceptions.RecoverableException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 * Window to make a report and send to tracemetrics developers. Require internet
 * connection.
 */
public class BugReport extends javax.swing.JFrame {

    //Static members
    private static final String NAME_TEXT_FIELD_DEFAULT = "Your name";
    private static final String MAIL_TEXT_FIELD_DEFAULT = "Your e-mail here";
    private static final String REGEX_USER = "^([à-üa-zA-ZÀ-Ü0-9]{1}[à-üa-zA-ZÀ-Ü0-9_\\.-]{0,}@)";
    private static final String REGEX_DOMAIN = "([^-@][à-üa-zA-ZÀ-ÜçÇ_0-9-]{0,24}[^-.])";
    private static final String REGEX_AUTHORITY = "(([a-zA-Z-]{2,})(\\b\\.[a-zA-Z]{2,}){0,7})$";
    private static final String REGEX_EMAIL = REGEX_USER + REGEX_DOMAIN + "\\." + REGEX_AUTHORITY;
//    private static final String SMTP_SERVER = "smtp2go.com";
//    private static final String SMTP_USER = "tracemetrics@tracemetrics.net";
//    private static final int SMTP_PORT = 2525;
    private static final String SMTP_SERVER = "relay.jangosmtp.net";
    private static final String SMTP_USER = "rulrok";
    private static final String SMTP_AUTH = "tracemetrics";
    private static final int SMTP_PORT = 25;
    //Object's members
    private boolean emailValid = true;
    private boolean emailOK = false;
    private boolean nameOK = false;
    private boolean textOK = false;
    private boolean detailsVisibilit = false;
    private Dimension textAreaHideDimension;
    private Dimension textAreaShowDimension;
    private Dimension windowShowDimension;
    private Dimension windowHideDimension;

    /**
     * Creates new form BugReport
     */
    public BugReport() {
        initComponents();
        jL_InvalidEmail.setVisible(false);
        jB_Details.setVisible(false);
        jB_Details.setEnabled(false);

        jTF_Email.setText(MAIL_TEXT_FIELD_DEFAULT);
        jTF_Name.setText(NAME_TEXT_FIELD_DEFAULT);

        textAreaShowDimension = new Dimension(jTA_Details.getSize());
        textAreaHideDimension = new Dimension(jTA_Details.getSize().width, 0);
        windowShowDimension = new Dimension(this.getSize());
        windowHideDimension = new Dimension(windowShowDimension.width, windowShowDimension.height - textAreaShowDimension.height - 10);
        this.setSize(windowHideDimension);

        jTA_Details.setVisible(detailsVisibilit);
        jSP_Details.setVisible(detailsVisibilit);

        jTA_Details.setPreferredSize(textAreaHideDimension);
        jSP_Details.setPreferredSize(textAreaHideDimension);

        Point location = Utils.getCentralCoords(Toolkit.getDefaultToolkit().getScreenSize(), this.getBounds());
        this.setLocation(location);


    }

    /**
     * Creates new form BugReport with support to aditional information to send.
     *
     * @param details A string auto attached with the report; it's shown to
     * user.
     */
    public BugReport( String details ) {
        this();
        jB_Details.setVisible(true);
        jB_Details.setEnabled(true);
        jTA_Details.setText(null);
        jTA_Details.setText(details);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSP_Report = new javax.swing.JScrollPane();
        jTA_Report = new javax.swing.JTextArea();
        jTF_Name = new javax.swing.JTextField();
        jTF_Email = new javax.swing.JTextField();
        jB_Send = new javax.swing.JButton();
        jSP_Report1 = new javax.swing.JScrollPane();
        jTA_Report1 = new javax.swing.JTextArea();
        jB_Details = new javax.swing.JToggleButton();
        jSP_Details = new javax.swing.JScrollPane();
        jTA_Details = new javax.swing.JTextArea();
        jL_InvalidEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bug Report");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/gui/bug/mail_new.png"))); // NOI18N
        jLabel1.setText("BUG Report");

        jLabel2.setText("Please, make a descriptive relative of the encountered problem or suspect bug.");

        jSP_Report.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTA_Report.setColumns(20);
        jTA_Report.setRows(5);
        jTA_Report.setBorder(null);
        jTA_Report.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTA_ReportFocusLost(evt);
            }
        });
        jSP_Report.setViewportView(jTA_Report);

        jTF_Name.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTF_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_NameFocusLost(evt);
            }
        });

        jTF_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTF_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_EmailFocusLost(evt);
            }
        });

        jB_Send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analyzer/gui/bug/mail_forward.png"))); // NOI18N
        jB_Send.setText("Send");
        jB_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SendActionPerformed(evt);
            }
        });

        jSP_Report1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTA_Report1.setColumns(20);
        jTA_Report1.setRows(5);
        jTA_Report1.setBorder(null);
        jTA_Report1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTA_ReportFocusLost(evt);
            }
        });
        jSP_Report1.setViewportView(jTA_Report1);

        jB_Details.setText("Show details");
        jB_Details.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jB_DetailsItemStateChanged(evt);
            }
        });

        jSP_Details.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTA_Details.setColumns(20);
        jTA_Details.setEditable(false);
        jTA_Details.setRows(5);
        jTA_Details.setText("<Empty details>");
        jSP_Details.setViewportView(jTA_Details);

        jL_InvalidEmail.setForeground(new java.awt.Color(204, 0, 0));
        jL_InvalidEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_InvalidEmail.setText("Your e-mail not appear correct");
        jL_InvalidEmail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSP_Details)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_InvalidEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Send, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTF_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_Email))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSP_Report, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSP_Report, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_Email)
                    .addComponent(jTF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Send)
                    .addComponent(jL_InvalidEmail)
                    .addComponent(jB_Details))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSP_Details, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static Properties getProperties() {

        Properties properties = new Properties();
        properties.put("mail.smtp.host", SMTP_SERVER);
        properties.put("mail.smtp.socketFactory.port", SMTP_PORT);
        properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        properties.put("mail.smtp.user", SMTP_USER);
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.port", SMTP_PORT);

        return properties;
    }

    public static Authenticator getAuthenticator() {

        Authenticator autenticacao;
        autenticacao = new Authenticator() {

            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return super.getPasswordAuthentication();
            }
 };
        return autenticacao;
    }

    private void jB_SendActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_jB_SendActionPerformed
        Session session = Session.getInstance(getProperties());
        MimeMessage msg = new MimeMessage(session);



        try {
            if ( !validateTransaction() ) {
                RecoverableException incompletFields = new RecoverableException("Campos incorretos");
                throw incompletFields;
            }

            msg.setFrom(new InternetAddress(jTF_Name.getText() + " (" + jTF_Email.getText() + ") " + " <bugreport@tracemetrics.net>"));
            msg.setRecipient(Message.RecipientType.TO, new InternetAddress("Trace Metrics <tracemetrics@tracemetrics.net>"));
            msg.setSentDate(new Date());
            msg.setSubject("Bug Report!");
            msg.setText(jTA_Report.getText() + "\n\nAditional Information:\n" + jTA_Details.getText());
            msg.saveChanges();

            Transport tr = session.getTransport("smtp");
            tr.connect(SMTP_SERVER, SMTP_USER, SMTP_AUTH);
            tr.sendMessage(msg, msg.getAllRecipients());
            tr.close();
            
            javax.swing.JOptionPane.showMessageDialog(this, "E-mail was delivery successfully.\nWe will evaluate your report and provide the necessary corrections as soon as possible.");
            this.dispose();
        }
        catch ( RecoverableException recoverableException ) {
            recoverableException.printStackTrace();
        }
        catch ( MessagingException messagingException ) {
            messagingException.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Some problem occurred.\n Verify your internet connection and try later.");
        }

    }//GEN-LAST:event_jB_SendActionPerformed

    private boolean validateTransaction() {
        if ( emailOK && nameOK && textOK ) {
            jTF_Email.setBackground(Color.white);
            jTF_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
            jTF_Name.setBackground(Color.white);
            jTF_Name.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
            jTA_Report.setBackground(Color.white);
            jSP_Report.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
            return true;
        }
        else {
            if ( !emailOK ) {
                jTF_Email.setBackground(new Color(255, 190, 190));
                jTF_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder(Color.RED, null));
                if ( !emailValid ) {
                    jL_InvalidEmail.setVisible(true);
                }
            }
            else {
                jL_InvalidEmail.setVisible(false);
            }
            if ( !nameOK ) {
                jTF_Name.setBackground(new Color(255, 190, 190));
                jTF_Name.setBorder(javax.swing.BorderFactory.createEtchedBorder(Color.RED, null));
            }
            if ( !textOK ) {
                jTA_Report.setBackground(new Color(255, 190, 190));
                jSP_Report.setBorder(javax.swing.BorderFactory.createEtchedBorder(Color.RED, null));
            }
            return false;
        }
    }

    private void jTF_NameFocusGained( java.awt.event.FocusEvent evt ) {//GEN-FIRST:event_jTF_NameFocusGained
        if ( jTF_Name.getText().equals(NAME_TEXT_FIELD_DEFAULT) ) {
            jTF_Name.setText(null);
            nameOK = false;
        }
    }//GEN-LAST:event_jTF_NameFocusGained

    private void jTF_NameFocusLost( java.awt.event.FocusEvent evt ) {//GEN-FIRST:event_jTF_NameFocusLost
        if ( jTF_Name.getText().trim().isEmpty() ) {
            jTF_Name.setText(NAME_TEXT_FIELD_DEFAULT);
            nameOK = false;
        }
        else {
            nameOK = true;
        }
        jTF_Name.setBackground(Color.white);
        jTF_Name.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
    }//GEN-LAST:event_jTF_NameFocusLost

    private void jTF_EmailFocusGained( java.awt.event.FocusEvent evt ) {//GEN-FIRST:event_jTF_EmailFocusGained
        if ( jTF_Email.getText().equals(MAIL_TEXT_FIELD_DEFAULT) ) {
            jTF_Email.setText(null);
            emailOK = false;
        }
    }//GEN-LAST:event_jTF_EmailFocusGained

    private void jTF_EmailFocusLost( java.awt.event.FocusEvent evt ) {//GEN-FIRST:event_jTF_EmailFocusLost
        if ( jTF_Email.getText().trim().isEmpty() ) {
            jTF_Email.setText(MAIL_TEXT_FIELD_DEFAULT);
            jTF_Email.setBackground(Color.WHITE);
            jTF_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
            emailOK = false;
            emailValid = true;
        }
        else if ( jTF_Email.getText().matches(REGEX_EMAIL) ) {
            jTF_Email.setBackground(Color.WHITE);
            jTF_Email.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
            emailOK = true;
            emailValid = true;
        }
        else { //Invalid email
            jTF_Email.setBackground(new Color(255, 190, 190));
            emailOK = false;
            emailValid = false;
        }
    }//GEN-LAST:event_jTF_EmailFocusLost

    private void jB_DetailsItemStateChanged( java.awt.event.ItemEvent evt ) {//GEN-FIRST:event_jB_DetailsItemStateChanged
        detailsVisibilit = !detailsVisibilit;
        jSP_Details.setVisible(detailsVisibilit);
        jTA_Details.setVisible(detailsVisibilit);

        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            jSP_Details.setSize(textAreaShowDimension);
            jTA_Details.setSize(textAreaShowDimension);
            this.setSize(windowShowDimension);
            Point location = Utils.getCentralCoords(Toolkit.getDefaultToolkit().getScreenSize(), this.getBounds());
            this.setLocation(location);
        }
        else {
            jSP_Details.setSize(textAreaHideDimension);
            jTA_Details.setSize(textAreaHideDimension);
            this.setSize(windowHideDimension);
            Point location = Utils.getCentralCoords(Toolkit.getDefaultToolkit().getScreenSize(), this.getBounds());
            this.setLocation(location);
        }
    }//GEN-LAST:event_jB_DetailsItemStateChanged

    private void jTA_ReportFocusLost( java.awt.event.FocusEvent evt ) {//GEN-FIRST:event_jTA_ReportFocusLost
        jTA_Report.setBackground(Color.white);
        jSP_Report.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, null));
        if ( jTA_Report.getText().trim().isEmpty() ) {
            textOK = false;
        }
        else {
            textOK = true;
        }
    }//GEN-LAST:event_jTA_ReportFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals(info.getName()) ) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger(BugReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger(BugReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger(BugReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger(BugReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BugReport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jB_Details;
    private javax.swing.JButton jB_Send;
    private javax.swing.JLabel jL_InvalidEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jSP_Details;
    private javax.swing.JScrollPane jSP_Report;
    private javax.swing.JScrollPane jSP_Report1;
    private javax.swing.JTextArea jTA_Details;
    private javax.swing.JTextArea jTA_Report;
    private javax.swing.JTextArea jTA_Report1;
    private javax.swing.JTextField jTF_Email;
    private javax.swing.JTextField jTF_Name;
    // End of variables declaration//GEN-END:variables
}
